nemoAddNeuron.m
nemoAddSynapse.m
nemoNeuronCount.m
nemoClearNetwork.m
nemoSetCpuBackend.m
nemoSetCudaBackend.m
nemoSetStdpFunction.m
nemoBackendDescription.m
nemoSetWriteOnlySynapses.m
nemoResetConfiguration.m
nemoStep.m
nemoApplyStdp.m
nemoGetSynapsesFrom.m
nemoGetTargets.m
nemoGetDelays.m
nemoGetWeights.m
nemoGetPlastic.m
nemoElapsedWallclock.m
nemoElapsedSimulation.m
nemoResetTimer.m
nemoCreateSimulation.m
nemoDestroySimulation.m
nemoReset.m